10. Publik Web (Home)
aldhi88/5sore_apotek_template pull request #1
Opened 2023-12-01 01:48 UTC by MhdFikri44

silahkan di cek pak @aldhi88 
![image](https://github.com/aldhi88/5sore_apotek_template/assets/130049564/78847403-d215-4214-ad06-8e151b901b47)

2023-12-01 04:03 UTC, aldhi88 requested changes
@MhdFikri44 perbaiki ya

2023-12-01 04:03 UTC, aldhi88 commented on index.html
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" cross
BS nya arahkan ke aset lokal di folder lib @MhdFikri44

2023-12-01 11:43 UTC, MhdFikri44 commented on index.html
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" cross
Di download dulu berarti file bootsrapnya pak

2023-12-02 04:13 UTC, aldhi88 approved these changes

2023-12-02 04:14 UTC, merged